---
- name: galaxy
  hosts: galaxyservers
  vars:
    galaxy_server_dir: /evol/srv/galaxy/galcode
    galaxy_root: /evol/srv/galaxy
    galaxy_instance_hostname: ross.genomicsvl-students.cloud.edu.au
    galaxy_config_admin_users: "ross.lazarus@gmail.com,admin@galaxy.org"
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'virtualenv']
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - gantsign.golang
    - cyverse-ansible.singularity
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - galaxyproject.cvmfs
#    - geerlingguy.docker
#    - usegalaxy_eu.gie_proxy

