# CVMFS vars
cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: 5000

# Galaxy vars that will be reused by Pulsar
galaxy_job_metrics_plugins:
  - type: core
  - type: cpuinfo
  - type: meminfo
  - type: uname
  - type: env
  - type: cgroup
  - type: hostname

# Telegraf
telegraf_agent_package_state: latest

# Configure the output to point to an InfluxDB
# running on localhost, and # place data in the
# database "telegraf" which will be created if need be.
telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["http://127.0.0.1:8086"]
    - database = "telegraf"

# The default plugins, applied to any telegraf-configured host
telegraf_plugins_default:
  - plugin: cpu
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
