---
# material from https://github.com/galaxyproject/usegalaxy-playbook/blob/main/env/testtoolshed/group_vars/toolshedservers/vars.yml
# Tool Shed version
# "--bind=localhost:9009 --config /evol/ts/galaxy/galcode/lib/galaxy/web_stack/gunicorn_config.py"
galaxy_commit_id: release_22.01

# tool_shed.yml contents

galaxy_toolshed_config:
  gunicorn:
    bind: localhost:9009
    config: "{{ galaxy_server_dir }}/lib/galaxy/web_stack/gunicorn_config.py"
    gunicorn_extra_args: '--forwarded-allow-ips="*"'

  tool_shed:
    # secrets
    id_secret: "{{ galaxy_toolshed_config_id_secret }}"
    admin_users: "{{ galaxy_toolshed_config_admin_users }}"
    galaxy_separate_privileges: false
    # paths

    file_path: "/evol/ts/{{ galaxy_toolshed_instance_codename }}"
    new_file_path: "{{ galaxy_toolshed_mutable_data_dir }}/tmp"
    tool_data_path: "{{ galaxy_toolshed_mutable_data_dir }}/tool-data"

    # general stuff
    database_connection: "sqlite:///./database/community.sqlite?isolation_level=IMMEDIATE"
    #database_connection: "postgresql:///galaxy_testtoolshed?host=/var/run/postgresql"
    # database_engine_option_server_side_cursors: "True"
    log_level: "DEBUG"
    debug: "False"
    use_lint: "False"
    num_tool_test_results_saved: "5"
    support_url: "https://galaxyproject.org/support"
    smtp_server: "smtp.psu.edu"
    email_from: "galaxy-no-reply@toolshed.g2.bx.psu.edu"
    brand: 'RossToolShed'

    # stuff that shouldn't be here but maybe has to
    conda_auto_init: false
    tool_dependency_dir: "{{ galaxy_toolshed_mutable_data_dir }}/dependencies"

certbot_domains:
  - "{{ inventory_hostname }}"
#material from https://github.com/galaxyproject/usegalaxy-playbook/blob/main/env/common/group_vars/toolshedwebservers.yml
nginx_enable_default_server: false

nginx_conf_ssl_protocols:
    - TLSv1.2

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 64M
  proxy_read_timeout: 3600
  uwsgi_read_timeout: 600
  gzip_vary: 'on'
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_buffers: 16 8k
  gzip_http_version: 1.1
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript

